#ifndef DEVICE_ENUM_HPP
#define DEVICE_ENUM_HPP

enum TTYDevice {
    USB, ACM
};

enum ResultType {
    LAST_RESULT_ONLY, WHOLE_RESULT, EXECUTE_ONLY
};

enum Mode {
    SINGLE_MODE, MULTI_MODE, DELETE_MODE, INPUT_MODE
};

#endif // DEVICE_ENUM_HPP
